"use client";

import Link from "next/link";
import { FaArrowLeft, FaArrowRight, FaCheck, FaEnvelope, FaGraduationCap, FaNetworkWired } from "react-icons/fa";
import { dokiProfileContent } from "@/content/doki-profile-content";
import WorldNav from "@/components/site/WorldNav";
import SiteFooter from "@/components/site/SiteFooter";
import { FadeZoom, Stagger, StaggerItem } from "@/components/motion/FadeZoom";

export default function EngineeringProfilePage({ locale }) {
  const c = dokiProfileContent[locale].engineering;
  return <div className="claris-page min-h-screen overflow-x-clip text-slate-100"><WorldNav locale={locale} world="doki" />
    <main className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24">
      <FadeZoom as="header" className="grid gap-12 border-b border-white/10 pb-16 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-teal-300">{c.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-light leading-[.98] tracking-[-.045em] sm:text-7xl">{c.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">{c.intro}</p><p className="mt-7 inline-flex items-center gap-2 rounded-full border border-teal-300/25 bg-teal-300/10 px-4 py-2 text-[10px] font-bold uppercase tracking-[.15em] text-teal-100"><span className="h-2 w-2 rounded-full bg-teal-300" />{c.availability}</p></div><div className="claris-glass rounded-[2rem] border p-7"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-white/45">{c.resume}</p><p className="mt-3 text-sm leading-6 text-slate-400">{c.resumeHint}</p><button disabled aria-disabled="true" className="mt-7 inline-flex min-h-11 cursor-not-allowed items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-5 text-[10px] font-bold uppercase tracking-[.15em] text-white/35"><FaArrowRight />{c.resume}</button></div></FadeZoom>
      <section className="grid gap-5 py-20 lg:grid-cols-[1fr_.9fr]"><FadeZoom><p className="text-xs font-bold uppercase tracking-[.28em] text-teal-300">{c.summaryLabel}</p><h2 className="mt-4 text-4xl font-light tracking-tight">{c.summaryTitle}</h2><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300">{c.summary}</p></FadeZoom><FadeZoom delay={.08}><div className="claris-glass rounded-3xl border p-7"><FaGraduationCap className="h-5 w-5 text-teal-300" /><p className="mt-6 text-[10px] font-bold uppercase tracking-[.2em] text-teal-200">{c.educationLabel}</p><p className="mt-3 text-xl text-white">{c.education}</p><dl className="mt-8 grid gap-5 border-t border-white/10 pt-6 sm:grid-cols-2"><div><dt className="text-[10px] font-bold uppercase tracking-[.15em] text-white/45">{c.completionLabel}</dt><dd className="mt-2 text-sm text-white">{c.completion}</dd></div><div><dt className="text-[10px] font-bold uppercase tracking-[.15em] text-white/45">{c.graduationLabel}</dt><dd className="mt-2 text-sm text-white">{c.graduation}</dd></div></dl></div></FadeZoom></section>
      <section className="border-y border-white/10 py-20"><FadeZoom><p className="text-xs font-bold uppercase tracking-[.28em] text-sky-300">{c.skillsLabel}</p><h2 className="mt-4 text-4xl font-light tracking-tight sm:text-5xl">{c.skillsTitle}</h2></FadeZoom><Stagger className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{c.skills.map((skill) => <StaggerItem key={skill}><article className="claris-glass h-full rounded-3xl border p-6"><FaNetworkWired className="h-5 w-5 text-teal-300" /><h3 className="mt-8 text-lg text-white">{skill}</h3><p className="mt-3 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.15em] text-white/45"><FaCheck className="text-teal-300" />{c.currentFocus}</p></article></StaggerItem>)}</Stagger></section>
      <section className="py-20"><FadeZoom><p className="text-xs font-bold uppercase tracking-[.28em] text-fuchsia-200">{c.evidenceLabel}</p><h2 className="mt-4 text-4xl font-light tracking-tight sm:text-5xl">{c.evidenceTitle}</h2></FadeZoom><Stagger className="mt-10 grid gap-4 md:grid-cols-3">{c.placeholders.map((item) => <StaggerItem key={item.title}><article className="claris-glass h-full rounded-3xl border p-7"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-white/40">{c.comingNext}</p><h3 className="mt-5 text-xl font-light text-white">{item.title}</h3><p className="mt-4 text-sm leading-7 text-slate-400">{item.text}</p></article></StaggerItem>)}</Stagger></section>
      <FadeZoom><section className="claris-glass rounded-[2rem] border bg-gradient-to-br from-teal-300/10 to-transparent p-8 text-center sm:p-14"><p className="text-xs font-bold uppercase tracking-[.28em] text-teal-300">{c.contactLabel}</p><h2 className="mt-4 text-4xl font-light tracking-tight sm:text-5xl">{c.contactTitle}</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-slate-300">{c.contactText}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="mailto:dokkdokki@dokimachine.net" className="claris-flow-button inline-flex min-h-11 items-center gap-3 rounded-full px-6 py-3 text-[10px] font-bold uppercase tracking-[.15em]"><FaEnvelope />{c.contact}</a><Link href={`/${locale}/doki`} className="inline-flex min-h-11 items-center gap-3 rounded-full border border-white/15 px-6 py-3 text-[10px] font-bold uppercase tracking-[.15em] text-white/75 transition hover:border-teal-300 hover:text-teal-200"><FaArrowLeft />{c.back}</Link></div></section></FadeZoom>
    </main>
    <SiteFooter locale={locale} />
  </div>;
}
